feat(credentials): store and processing generic app credentials
waku-org/nwaku pull request #1466
Opened 2022-12-15 00:47 UTC by s1fr0

This PR adds a dynamic keystore for membership credential storage and management. The credentials are thought to be generic membership credentials, i.e. associated to a membership contract and membership Merkle tree, and the implementation is not tied to RLN credentials only.

The keystore JSON schema implemented is the one proposed in https://github.com/waku-org/nwaku/issues/1238#issuecomment-1278114079. 

In short, a keystore is uniquely identified by an application name, app identifier and version strings. Multiple keystores can co-exist in the same file.
Each keystore can contain none or more Membership credentials. Each Membership Credential contains a unique Identity Credential (made of identity trapdoor, nullifier, secret hash and commitment) and none or more Membership Groups. Each Membership Group contains a Membership contract and a membership tree index position. A Membership Contract contains the chain ID and the membership contract address information.

When a Membership credential is added to a certain keystore: 
- if its Identity Credential was present in the keystore (it decrypts with the same password used to add the new credential), only the new Membership Groups (i.e. not already present in the keystore) will be added;
- if not present, the whole credential is added.
When one or more credentials are added, the keystore is automatically updated to disk (with a backup mechanism to mitigate credentials loss in case of IO errors).

Membership credentials in a certain keystore can be retrieved by none or more filters. These allow to return:
- all Membership credentials decrypting under a certain password;
- Membership credentials corresponding to one or more Identity credentials;
- Membership credentials corresponding to one or more Membership Groups (non-matching groups are stripped);
- Membership credentials corresponding to one or more Identity credentials and Membership Groups (non-matching groups are stripped).

This PR addresses the issues:
  - [x] https://github.com/vacp2p/rfc/issues/543
  - [x] https://github.com/status-im/nwaku/issues/1238
  - [x] https://github.com/status-im/nwaku/issues/1278

2022-12-15 23:17 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | b6466f68 | [#1](https://ci.status.im/job/nim-waku/job/prs/job/macos/job/PR-1466/1/) | 2022-12-15 23:17:24 | ~30 min | `macos` | [:package:`bin`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/wakunode2-221215-224715-b6466f-macos.bin) |

2023-01-12 10:54 UTC, jm-clius commented
@s1fr0 @rymnc I notice this draft PR has a release milestone attached - should we remove the milestone (not required for PRs, but rather for issues), or bump it to a next milestone?

2023-01-31 05:30 UTC, rymnc reviewed
Few queries, looks great!

Maybe we should decide if we plan to merge this, or #1496 first. There would be non-trivial refactoring both ways.

2023-01-31 05:30 UTC, rymnc commented on waku/v2/node/waku_node.nim
> +  await peer_manager.connectToNodes(node.peerManager, nodes, WakuRelayCodec, source=source)
Is this change required?

2023-01-31 05:30 UTC, rymnc commented on waku/v2/utils/credentials.nim
> +  address*: string
```suggestion
type ContractReference* = object
  chainId*: string
  address*: string
```

2023-01-31 05:30 UTC, rymnc commented on waku/v2/utils/credentials.nim
> +                      version: string,
Can this be a single object? `AppConfig` or similar

2023-01-31 05:30 UTC, rymnc commented on waku/v2/utils/credentials.nim
> +           data["version"].getStr() == version:
Can you create a proc which checks if `data` contains all of the elements in ["application", "appIdentifier", "credentials", "version"]?

```nim
proc hasAllKeys(data: Table[string, JsonNode], keys: seq[string]): bool =
  return all(data.contains(key) : key in keys)
```

2023-01-31 05:30 UTC, rymnc commented on waku/v2/utils/credentials.nim
> +          let decodedCredential = decode(decodedKeyfile.get())
For all calls which return a `Result`, please append `Res` to the variable

2023-01-31 05:30 UTC, rymnc commented on waku/v2/utils/credentials.nim
> +proc addMembershipCredentials*(path: string,
Can we shorten this proc? It's > 100 loc :)

2023-01-31 13:25 UTC, LNSD commented
Wow! +696 new lines! 😨

I will need a couple of days to review this. Let's keep the PR sizes manageable. Smaller PRs will help us be more agile in reviewing and merging code changes.

2023-01-31 13:27 UTC, rymnc commented on waku/v2/utils/credentials.nim
> +  address*: string
No strong opinion here, but MembershipContract can refer to the type of the contract itself (generated by nim-web3). This works too!

2023-02-06 12:17 UTC, rymnc approved these changes
LGTM, maybe we should have instructions for operators to use this feature :)

2023-02-06 15:08 UTC, LNSD requested changes
I find the code a little convoluted. Please, check my comments.

2023-02-06 15:08 UTC, LNSD commented on waku/v2/utils/credentials.nim
> +    ReadKeyfileError      = "Error while reading keyfile for credentials"
Could you separate the `AppKeystore` related code into another module?

2023-02-06 15:08 UTC, LNSD commented on waku/v2/utils/credentials.nim
> +  return all(keys, proc (key: string): bool = return data.hasKey(key))
All the JSON serialization-related code should be in a separate module.

2023-02-08 15:21 UTC, LNSD approved these changes
Thanks for adding it inside the `waku_keystore`. I like the new module layout.

There are minor/nitpick details, but in general, LGreatTM ✅

2023-02-08 15:26 UTC, merged