docs: mention cloning of submodules in README.md
waku-org/nwaku pull request #1524
Opened 2023-01-31 15:49 UTC by felicio

2023-01-31 23:17 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | e991f73e | [#1](https://ci.status.im/job/nim-waku/job/prs/job/macos/job/PR-1524/1/) | 2023-01-31 23:17:36 | ~30 min | `macos` | [:package:`bin`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/wakunode2-230131-224715-e991f7-macos.bin) |

2023-02-01 18:18 UTC, alrevuelta commented on README.md
> +git clone --recurse-submodules <REPOSITORY_REMOTE_URL>
Thanks, indeed missing. Can we add it right before `make wakunode1 wakunode2` in "Wakunode" section?

`make update` should e fine instead.

2023-02-02 16:18 UTC, LNSD commented
AFAIK this is not necessary, the makefile already does it for you if you run `make update` for the first time.

Here: https://github.com/waku-org/nwaku/blob/master/Makefile#L17-L26

2023-02-02 16:20 UTC, LNSD requested changes
AFAIK this is not necessary, the makefile already does it for you if you run `make update` for the first time.

You can clone the repo normally, and then run `make update`. The submodules will be cloned recursively.

----

The makefile relevant part: https://github.com/waku-org/nwaku/blob/master/Makefile#L17-L26

2023-02-02 16:25 UTC, alrevuelta commented on README.md
> +git clone --recurse-submodules <REPOSITORY_REMOTE_URL>
yup as @LNSD I think we should just add `make update`

2023-02-09 07:29 UTC, alrevuelta commented on README.md
> +git clone --recurse-submodules <REPOSITORY_REMOTE_URL>
@felicio Mind adding `make update`, so we can merge this? Thanks!

2023-03-03 09:08 UTC, closed without merging