feat(rln-relay): use precompiled resources w/ rln
waku-org/nwaku pull request #1578
Opened 2023-02-27 12:25 UTC by rymnc

!! Don't merge !!

Companion PR: https://github.com/vacp2p/zerokit/pull/118
This pr is used to test this change with CI. can be merged after zerokit's pr is merged

2023-03-03 14:16 UTC, rymnc commented on .gitmodules
> +	branch = staticlib
I'll update this after zerokit's pr is merged.

2023-03-03 14:30 UTC, jm-clius approved these changes
Thanks!

2023-03-03 15:25 UTC, LNSD requested changes
I noticed that you removed the experimental stage from the Dockerfile. That's a great improvement 👏🏼 

There are some remains in the `Makefile` (e.g., [these lines should be removed](https://github.com/waku-org/nwaku/pull/1578/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L233-L235)). Could you review the Makefile tasks?

2023-03-05 22:08 UTC, LNSD approved these changes
LGTM ✅

2023-03-07 12:47 UTC, rymnc commented
will merge since zerokit's pr has been merged

2023-03-13 06:33 UTC, merged