refactor: Waku Cache & New Architecture
waku-org/nwaku pull request #1962
Opened 2023-08-28 15:51 UTC by SionoiS

Opening this to get feedback on a new way to architecture Nwaku.

This serve just as an example. I use Chronos `AsyncEventQueue` as some kind of broadcast channel to send the information needed to various sub-systems.

Relay messages are sent to Waku Cache and also topic subscriptions they are then filtered and sent to Discv5 and Relay.
It allow for a slimmer `waku_node` too since `waku_node` no longer be called just to then call the inner protocols.

Please focus your attention on the information flow between; Discv5, Relay, Filter, LightPush and the APIs

Waku Cache could be removed if the topic filtering is duplicated in Relay and Discv5. the caches could also live somewhere else. 

WDYT?

---

P.S.

[Nimbus usage of AsyncEventQueue](https://github.com/search?q=repo%3Astatus-im%2Fnimbus-eth2%20AsyncEventQueue&type=code)

I also keep [notes](https://www.notion.so/S-P-s-Architectural-Notes-481dec3dc54d41ddba9f45e440f85bca) about the architecture of Nwaku. Feel free to add to it your wishes or observations.

2023-08-28 16:01 UTC, SionoiS commented
Tagging @NagyZoltanPeter @jm-clius @Ivansete-status

2023-08-29 07:26 UTC, Ivansete-status requested changes
Good morning! Thanks for this initiative!

Few points we need to address before

- I started the review but then I realized that the changes don't compile
- `AsyncEventQueue` seems not to be from the standard library. We need to ask Jacek or Zahary about introducing this concept in Waku, in case they see any possible drawback or flaw.
- I can't see where the messages are emitted in general. To me, it is difficult to follow the flow.

2023-08-29 11:27 UTC, SionoiS commented on waku/waku_cache.nim
> +    subscriptions: Table[PubsubTopic, tuple[manual: bool, count: int]]
Manual subscription to a shard AKA subcribe to a pubsub topic that is a shard define for the Waku Network.

2023-08-29 11:28 UTC, SionoiS commented on waku/waku_cache.nim
> +    wc.messageCache.subscribe(topic)
Yes exactly

2023-08-29 11:31 UTC, SionoiS commented on waku/waku_archive/archive.nim
> +    let events = await wa.messageQueue.waitEvents(key)
They are emitted in relay, but the goal is exactly to not care where they are emitted from. They could also come from light push.

2023-08-29 11:33 UTC, SionoiS commented on waku/waku_archive/archive.nim
> +  let key = wa.messageQueue.register()
I'll see what can be done

2023-08-29 11:36 UTC, SionoiS commented on waku/waku_archive/archive.nim
> +proc stop*(wa: WakuArchive) {.async.} = wa.started = false
:thinking: that's a good question there's probably a way to cancel futures no?

For archive, we could tie the periodic policy with the new lifecycle too.

2023-08-29 11:54 UTC, SionoiS commented
> * I started the review but then I realized that the changes don't compile

Yes just wanted to ask for feedback as the changes would be major.

> * `AsyncEventQueue` seems not to be from the standard library. We need to ask Jacek or Zahary about introducing this concept in Waku, in case they see any possible drawback or flaw.

I'm in contract with @cheatfate who authored `AsyncEventQueue` I asked for more details.

> * I can't see where the messages are emitted in general. To me, it is difficult to follow the flow.

Might be because the setup phase is missing. In `app` the various sub-systems would be initialized with the queues.

2023-08-29 12:00 UTC, SionoiS commented on waku/waku_archive/archive.nim
> +  messageQueue: AsyncEventQueue[(PubsubTopic, WakuMessage)],
My mistake

2023-08-29 17:53 UTC, jm-clius reviewed
Without reviewing the implementation details here, I think this is an architecture worth exploring provided we understand the `AsyncEventQueue` and impact. Since the specific problem you were trying to solve is simply related to listening to subscription changes, why not drop the `messageQueue` for now and only explore the `subscriptionQueue`? I'm also not sure about having everything into a single "WakuCache" - in future, perhaps just have different caches for subscriptions and messages with no need to combine them into a single structure?

2023-08-29 19:46 UTC, SionoiS commented
> Without reviewing the implementation details here, I think this is an architecture worth exploring provided we understand the `AsyncEventQueue` and impact. Since the specific problem you were trying to solve is simply related to listening to subscription changes, why not drop the `messageQueue` for now and only explore the `subscriptionQueue`?

Sounds reasonable.

> I'm also not sure about having everything into a single "WakuCache" - in future, perhaps just have different caches for subscriptions and messages with no need to combine them into a single structure?

It made sense at the time but yes it could be separate.

2023-08-29 23:40 UTC, SionoiS commented
> Since the specific problem you were trying to solve is simply related to listening to subscription changes, why not drop the `messageQueue` for now and only explore the `subscriptionQueue`?

Kinda hard to mix both.

> I'm also not sure about having everything into a single "WakuCache" - in future, perhaps just have different caches for subscriptions and messages with no need to combine them into a single structure?

Made sense to do it this way but it can be separate.

2023-09-05 19:04 UTC, SionoiS commented
I can still see many advantages to this but since we don't have `AsyncChannel[T]` yet, Nimbus team have a lot on their plate and I  haven't though about how to incrementally do it, I'm putting this on pause for now.

2023-09-08 14:04 UTC, Ivansete-status commented
> I gained knowledge about Nwaku in the process, that's a win for me, even if we never revisit this.

Yes indeed! That's a win for all of us of course! We can revisit this again once the `AsyncChannel[T]` gets more mature

2023-09-21 11:21 UTC, closed without merging