chore: return all connected peers from REST API
waku-org/nwaku pull request #2923
Opened 2024-07-19 22:42 UTC by weboko

# Description

Currently [GET `/admin/v1/peers`](https://waku-org.github.io/waku-rest-api/#get-/admin/v1/peers) has additional logic to build a list of peers service node is connected to. 
It does go through each group of protocols and builds a list:
https://github.com/waku-org/nwaku/blob/6d385cefef88ad80f41e830d904d68da596cbbde/waku/waku_api/rest/admin/handlers.nim#L43 

We can directly return list of connected peers as it more aligned with description of the endpoint: 
> Retrieve information about connected peers.

2024-07-19 23:39 UTC, NagyZoltanPeter requested changes
Sorry, but it is not working this way. We have a API response structure we must confirm with. So we return peers with their supported protocols.
This issue here - I think - that we won't return peers with protocol if the same protocol we don't support. (we = the node queried by GET /admin/peers). I think we should return all peers are connected and list all the protocols they support.

2024-07-22 12:40 UTC, NagyZoltanPeter commented
@weboko : Please check, I updated your PR with the thought functional change.
My question if this is enough for a client (admin) purposes. Do we really need all peers with all protocols?
cc: @jm-clius

2024-07-22 14:31 UTC, NagyZoltanPeter approved these changes

2024-07-22 14:36 UTC, gabrielmer approved these changes
LGTM, thank you!

Maybe we should add a test case for this?

2024-07-23 09:14 UTC, Ivansete-status approved these changes

2024-07-23 10:23 UTC, NagyZoltanPeter commented
> LGTM, thank you!
> 
> Maybe we should add a test case for this?

Yepp, done!

2024-07-23 10:58 UTC, merged