feat: waku store sync 2.0 common types & codec
waku-org/nwaku pull request #3213
Opened 2024-12-17 13:15 UTC by SionoiS

# Description

First PR for the new Waku Store Sync 2.0

Include types and encode/decode of payloads and also tests.

[Specification](https://github.com/waku-org/specs/blob/feat--waku-sync-2/standards/core/sync.md)
[Research issue](https://github.com/waku-org/research/issues/102)

# Changes

- [x] Common types
- [x] Codec
- [x] Tests

Followed by #3215

# Issue
- https://github.com/waku-org/nwaku/issues/3221

2024-12-17 16:37 UTC, gabrielmer reviewed
Amazinggg, thanks so much! 😍 

Honestly, I think I should understand more about range based reconciliation in order to follow what's going on here.

Any article or resource you recommend to read and use as a reference? I probably have some homework to do 😬

2024-12-17 16:37 UTC, gabrielmer commented on waku/waku_store_sync/codec.nim
> +  let capacity = 1 + (itemSet.elements.len * 41)
where does 41 come from?

2024-12-17 16:37 UTC, gabrielmer commented on waku/waku_store_sync/codec.nim
> +  #echo "First Timestamp: " & $lastTimestamp
There's lots of echo comments in this file that we should probably remove 😄

2025-01-06 13:41 UTC, SionoiS commented on waku/waku_store_sync/codec.nim
> +  #echo "First Timestamp: " & $lastTimestamp
LOL true! I'll remove those.

2025-01-06 13:45 UTC, SionoiS commented
> Amazinggg, thanks so much! 😍
> 
> Honestly, I think I should understand more about range based reconciliation in order to follow what's going on here.
> 
> Any article or resource you recommend to read and use as a reference? I probably have some homework to do 😬

The goto should my research issue. https://github.com/waku-org/research/issues/102

Although a lot of details are implementation specific which is not mentioned anywhere :thinking: maybe more code comment are needed.

2025-01-06 14:03 UTC, SionoiS commented on waku/waku_store_sync/codec.nim
> +  let capacity = 1 + (itemSet.elements.len * 41)
32 byte hash + 9 byte varint

2025-01-07 16:07 UTC, SionoiS commented on waku/waku_store_sync/common.nim
> +    fingerprint*: Fingerprint
I'm thinking of changing this as `fingerprint` should be used only for incremental not msg hashes.

2025-01-08 11:03 UTC, jm-clius requested changes
Thanks a lot for the (significant!) effort, also in the follow-up PRs! 🚀  I've requested some changes, mostly related to helping reviewers understand the code/protocol a bit better. For example, there are some magic numbers that I still can't quite figure out, some codec types don't quite match the spec or need some context, etc.

For this PR, I'd be happy to approve if the code is made clearer (with comments, reduced magic numbers, etc.). However, I think it will be easier for this (and follow-up) PRs to expand the wire protocol specification itself and get an agreed-upon design as spec first so that reviewers wouldn't have to infer how the protocol works only from code.

2025-01-08 12:38 UTC, SionoiS commented on waku/waku_store_sync/codec.nim
> +  let capacity = 1 + (itemSet.elements.len * 41)
I'll add a code comment.

It's just to avoid reallocation, it has nothing to do with the spec, it's not even necessary.

2025-01-08 13:13 UTC, SionoiS commented on waku/waku_store_sync/common.nim
> +    itemSets*: seq[ItemSet]
At this stage, the impl. is 100% equivalent to the previous one in features. There's no negotiation. We can start designing for limited shard support in my research issue if you want.

2025-01-08 16:16 UTC, SionoiS commented on waku/waku_store_sync/codec.nim
> +proc deltaDecode*(T: type SyncPayload, buffer: seq[byte]): T =
I don't think it's a good idea to add links in the code. Link always end up broken anyway.

Maybe a section at the top explaining that there's a spec?

2025-01-16 09:21 UTC, Ivansete-status commented on waku/waku_store_sync/common.nim
> +  ItemSet* = object
I think every type, and its procs, should be contained in a separate file

2025-01-16 14:39 UTC, SionoiS commented on waku/waku_store_sync/common.nim
> +  RetryDelay*: Duration = 30.seconds
Ah it's a left over and never used. I'll remove it.

2025-01-16 14:47 UTC, SionoiS commented on waku/waku_store_sync/common.nim
> +  ItemSet* = object
Come on, the file is not even 100 lines.

2025-01-17 13:30 UTC, Ivansete-status approved these changes
Thanks for it! Approving to not block it although I added a few nitpick comments that I hope you find interesting
Thanks for the patience!

2025-01-17 13:30 UTC, Ivansete-status commented on waku/waku_store_sync/codec.nim
> +      let itemSet = value.itemSets[j]
I'm a bit concerned about out-of-bounds issues in both `Fingerprint` and `ItemSet` ranges

2025-01-17 13:30 UTC, Ivansete-status commented on waku/waku_store_sync/codec.nim
> +proc deltaDecode*(T: type RangesData, buffer: seq[byte]): T =
May it be possible to split this proc a little? It is a little bit large and difficult to follow :)

2025-01-20 14:20 UTC, SionoiS commented on waku/waku_store_sync/codec.nim
> +  VarIntLen = 9
VarInts are max 9 bytes to express big numbers, since each byte use only 7 bits.

2025-01-20 14:23 UTC, SionoiS commented on waku/waku_store_sync/codec.nim
> +    let timeDiff = uint64(id.time) - uint64(lastTime)
:thinking: we could use seconds instead of nanos. Time diffs would be smaller but hashes would have to be included more often, so IDK if it's worth it.

2025-01-20 14:32 UTC, SionoiS commented on waku/waku_store_sync/codec.nim
> +    if timeDiff == 0:
It can because our timestamp have nano precision but half seconds accuracy.

2025-01-20 14:36 UTC, SionoiS commented on waku/waku_store_sync/codec.nim
> +      let itemSet = value.itemSets[j]
You can't go out of bound because the outer loop is visiting each ranges.

2025-01-20 21:21 UTC, NagyZoltanPeter commented on waku/waku_store_sync/codec.nim
> +proc deltaDecode*(T: type RangesData, buffer: seq[byte]): T =
Maybe, not just split this proc, but for me it is not obvious how it prevents malicious flows in the decoded buffer. 
Sure I miss something, but how do we validate the correctness of the input here?
This relates somehow the raised concern by @Ivansete-status that how are we sure the Ranges/Itemsets and fingerprints are correct and no over indexing could happen. (https://github.com/waku-org/nwaku/pull/3213/files/f2f0e648236eb5bad4745208368defe93585329f#r1920192288)

2025-01-20 21:29 UTC, SionoiS commented on waku/waku_store_sync/codec.nim
> +proc deltaDecode*(T: type RangesData, buffer: seq[byte]): T =
In the case of specifically sending malicious payload?

Yes in that case your right, we have a problem. I'll try to think of something.

2025-01-21 15:50 UTC, SionoiS commented on waku/waku_store_sync/codec.nim
> +proc deltaDecode*(T: type RangesData, buffer: seq[byte]): T =
@NagyZoltanPeter and @Ivansete-status I made sure that no malformed data can crash the decoder.

2025-01-22 04:57 UTC, NagyZoltanPeter approved these changes
Thanks for it, after the revised decoding I think it is ok!

2025-01-22 13:23 UTC, jm-clius approved these changes
Thanks!

2025-01-22 16:08 UTC, merged